version: '3.8'

services:
  qc_app_db:
    image: mysql:latest
    container_name: qc_app_db
    restart: unless-stopped
    ports:
      - '3305:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qc_app
      MYSQL_USER: hazi
      MYSQL_PASSWORD: Qwerty@123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
